export const users = [
  {
    id: 1,
    name: "John Doe",
    age: 28,
    phone: "+233 24 123 4567",
    email: "john.doe@example.com",
    profilePic: "https://randomuser.me/api/portraits/men/1.jpg",
    invitees: [
      {
        id: 9,
        name: "David Lee",
        age: 35,
        phone: "+233 27 321 7890",
        email: "david.lee@example.com",
        profilePic: "https://randomuser.me/api/portraits/men/9.jpg",
        invitees: [],
      },
      {
        id: 10,
        name: "Sarah Connor",
        age: 27,
        phone: "+233 26 876 5432",
        email: "sarah.c@example.com",
        profilePic: "https://randomuser.me/api/portraits/women/10.jpg",
        invitees: [],
      },
      {
        id: 11,
        name: "James Brown",
        age: 40,
        phone: "+233 23 234 5678",
        email: "james.b@example.com",
        profilePic: "https://randomuser.me/api/portraits/men/11.jpg",
        invitees: [],
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 32,
    phone: "+233 50 987 6543",
    email: "jane.smith@example.com",
    profilePic: "https://randomuser.me/api/portraits/women/2.jpg",
    invitees: [
      {
        id: 12,
        name: "Sophia Martinez",
        age: 30,
        phone: "+233 56 789 0123",
        email: "sophia.m@example.com",
        profilePic: "https://randomuser.me/api/portraits/women/12.jpg",
        invitees: [],
      },
      {
        id: 13,
        name: "Daniel White",
        age: 33,
        phone: "+233 54 567 8901",
        email: "daniel.w@example.com",
        profilePic: "https://randomuser.me/api/portraits/men/13.jpg",
        invitees: [],
      },
      {
        id: 14,
        name: "Olivia Taylor",
        age: 26,
        phone: "+233 25 098 7654",
        email: "olivia.t@example.com",
        profilePic: "https://randomuser.me/api/portraits/women/14.jpg",
        invitees: [],
      },
    ],
  },
  {
    id: 3,
    name: "Michael Johnson",
    age: 25,
    phone: "+233 20 456 7890",
    email: "michael.j@example.com",
    profilePic: "https://randomuser.me/api/portraits/men/3.jpg",
    invitees: [
      {
        id: 15,
        name: "Emily Watson",
        age: 29,
        phone: "+233 55 654 3210",
        email: "emily.w@example.com",
        profilePic: "https://randomuser.me/api/portraits/women/15.jpg",
        invitees: [],
      },
      {
        id: 16,
        name: "William Brown",
        age: 34,
        phone: "+233 30 111 2222",
        email: "william.b@example.com",
        profilePic: "https://randomuser.me/api/portraits/men/16.jpg",
        invitees: [],
      },
      {
        id: 17,
        name: "Ava Williams",
        age: 31,
        phone: "+233 20 333 4444",
        email: "ava.w@example.com",
        profilePic: "https://randomuser.me/api/portraits/women/17.jpg",
        invitees: [],
      },
    ],
  },
  {
    id: 4,
    name: "David Parker",
    age: 34,
    phone: "+233 30 111 8888",
    email: "david.p@example.com",
    profilePic: "https://randomuser.me/api/portraits/men/4.jpg",
    invitees: [
      {
        id: 18,
        name: "Charlotte Evans",
        age: 28,
        phone: "+233 24 444 5555",
        email: "charlotte.e@example.com",
        profilePic: "https://randomuser.me/api/portraits/women/18.jpg",
        invitees: [],
      },
      {
        id: 19,
        name: "Lucas Adams",
        age: 30,
        phone: "+233 23 666 7777",
        email: "lucas.a@example.com",
        profilePic: "https://randomuser.me/api/portraits/men/19.jpg",
        invitees: [],
      },
      {
        id: 20,
        name: "Isabella Wright",
        age: 29,
        phone: "+233 55 111 2222",
        email: "isabella.w@example.com",
        profilePic: "https://randomuser.me/api/portraits/women/20.jpg",
        invitees: [],
      },
    ],
  },
  {
    id: 5,
    name: "Ethan Walker",
    age: 32,
    phone: "+233 50 333 4444",
    email: "ethan.w@example.com",
    profilePic: "https://randomuser.me/api/portraits/men/5.jpg",
    invitees: [
      {
        id: 21,
        name: "Zoe Nelson",
        age: 27,
        phone: "+233 26 999 1111",
        email: "zoe.n@example.com",
        profilePic: "https://randomuser.me/api/portraits/women/21.jpg",
        invitees: [],
      },
      {
        id: 22,
        name: "Nathan Brooks",
        age: 35,
        phone: "+233 24 888 7777",
        email: "nathan.b@example.com",
        profilePic: "https://randomuser.me/api/portraits/men/22.jpg",
        invitees: [],
      },
      {
        id: 23,
        name: "Liam Carter",
        age: 30,
        phone: "+233 50 222 9999",
        email: "liam.c@example.com",
        profilePic: "https://randomuser.me/api/portraits/men/23.jpg",
        invitees: [],
      },
    ],
  },
  {
    id: 6,
    name: "Mia Thompson",
    age: 29,
    phone: "+233 55 222 9999",
    email: "mia.t@example.com",
    profilePic: "https://randomuser.me/api/portraits/women/6.jpg",
    invitees: [
      {
        id: 24,
        name: "Lucas Miller",
        age: 31,
        phone: "+233 23 777 8888",
        email: "lucas.m@example.com",
        profilePic: "https://randomuser.me/api/portraits/men/24.jpg",
        invitees: [],
      },
      {
        id: 25,
        name: "Sophia Walker",
        age: 32,
        phone: "+233 50 444 6666",
        email: "sophia.w@example.com",
        profilePic: "https://randomuser.me/api/portraits/women/25.jpg",
        invitees: [],
      },
      {
        id: 26,
        name: "Noah Scott",
        age: 33,
        phone: "+233 24 555 1111",
        email: "noah.s@example.com",
        profilePic: "https://randomuser.me/api/portraits/men/26.jpg",
        invitees: [],
      },
    ],
  },
];

export default users;
