export const users = [
  {
    id: 1,
    name: "John Doe",
    age: 28,
    phone: "+233 24 123 4567",
    email: "john.doe@example.com",
    profilePic: "https://randomuser.me/api/portraits/men/1.jpg",
    invitees: [
      {
        id: 7,
        name: "David Lee",
        age: 35,
        phone: "+233 27 321 7890",
        email: "david.lee@example.com",
        profilePic: "https://randomuser.me/api/portraits/men/5.jpg",
        invitees: [
          {
            id: 13,
            name: "Ethan Walker",
            phone: "+233 50 333 4444",
            profilePic: "https://randomuser.me/api/portraits/men/6.jpg",
          },
          {
            id: 14,
            name: "Mia Thompson",
            phone: "+233 55 222 9999",
            profilePic: "https://randomuser.me/api/portraits/women/7.jpg",
          },
          {
            id: 15,
            name: "Lucas Adams",
            phone: "+233 59 111 8888",
            profilePic: "https://randomuser.me/api/portraits/men/8.jpg",
          },
        ],
      },
      {
        id: 8,
        name: "Sarah Connor",
        age: 27,
        phone: "+233 26 876 5432",
        email: "sarah.c@example.com",
        profilePic: "https://randomuser.me/api/portraits/women/9.jpg",
        invitees: [
          {
            id: 16,
            name: "Sophia Martinez",
            phone: "+233 56 789 0123",
            profilePic: "https://randomuser.me/api/portraits/women/10.jpg",
          },
          {
            id: 17,
            name: "Nathan Brooks",
            phone: "+233 54 567 7777",
            profilePic: "https://randomuser.me/api/portraits/men/11.jpg",
          },
          {
            id: 18,
            name: "Charlotte Evans",
            phone: "+233 20 999 8888",
            profilePic: "https://randomuser.me/api/portraits/women/12.jpg",
          },
        ],
      },
      {
        id: 9,
        name: "James Brown",
        age: 40,
        phone: "+233 23 234 5678",
        email: "james.b@example.com",
        profilePic: "https://randomuser.me/api/portraits/men/13.jpg",
        invitees: [
          {
            id: 19,
            name: "Isabella Wright",
            phone: "+233 25 444 7777",
            profilePic: "https://randomuser.me/api/portraits/women/14.jpg",
          },
          {
            id: 20,
            name: "Noah Carter",
            phone: "+233 55 666 9999",
            profilePic: "https://randomuser.me/api/portraits/men/15.jpg",
          },
          {
            id: 21,
            name: "Zoe Mitchell",
            phone: "+233 24 777 5555",
            profilePic: "https://randomuser.me/api/portraits/women/16.jpg",
          },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 32,
    phone: "+233 50 987 6543",
    email: "jane.smith@example.com",
    profilePic: "https://randomuser.me/api/portraits/women/2.jpg",
    invitees: [
      {
        id: 22,
        name: "Emma Davis",
        phone: "+233 24 123 9999",
        profilePic: "https://randomuser.me/api/portraits/women/17.jpg",
      },
      {
        id: 23,
        name: "Daniel White",
        phone: "+233 50 333 1111",
        profilePic: "https://randomuser.me/api/portraits/men/18.jpg",
      },
      {
        id: 24,
        name: "Olivia Taylor",
        phone: "+233 20 999 7777",
        profilePic: "https://randomuser.me/api/portraits/women/19.jpg",
      },
    ],
  },
  {
    id: 3,
    name: "Michael Johnson",
    age: 25,
    phone: "+233 20 456 7890",
    email: "michael.j@example.com",
    profilePic: "https://randomuser.me/api/portraits/men/3.jpg",
    invitees: [
      {
        id: 25,
        name: "Amelia Brown",
        phone: "+233 23 555 6666",
        profilePic: "https://randomuser.me/api/portraits/women/20.jpg",
      },
      {
        id: 26,
        name: "William Harris",
        phone: "+233 55 777 8888",
        profilePic: "https://randomuser.me/api/portraits/men/21.jpg",
      },
      {
        id: 27,
        name: "Henry Adams",
        phone: "+233 24 999 5555",
        profilePic: "https://randomuser.me/api/portraits/men/22.jpg",
      },
    ],
  },
  {
    id: 4,
    name: "David Parker",
    age: 34,
    phone: "+233 30 111 8888",
    email: "david.p@example.com",
    profilePic: "https://randomuser.me/api/portraits/men/4.jpg",
    invitees: [
      {
        id: 28,
        name: "Elijah Martin",
        phone: "+233 20 333 2222",
        profilePic: "https://randomuser.me/api/portraits/men/23.jpg",
      },
      {
        id: 29,
        name: "Chloe Wilson",
        phone: "+233 24 111 7777",
        profilePic: "https://randomuser.me/api/portraits/women/24.jpg",
      },
      {
        id: 30,
        name: "Jackson Moore",
        phone: "+233 50 555 4444",
        profilePic: "https://randomuser.me/api/portraits/men/25.jpg",
      },
    ],
  },
  {
    id: 5,
    name: "Emily Watson",
    age: 29,
    phone: "+233 55 654 3210",
    email: "emily.w@example.com",
    profilePic: "https://randomuser.me/api/portraits/women/5.jpg",
    invitees: [
      {
        id: 31,
        name: "Hannah Clark",
        phone: "+233 23 222 9999",
        profilePic: "https://randomuser.me/api/portraits/women/26.jpg",
      },
      {
        id: 32,
        name: "Benjamin Allen",
        phone: "+233 55 888 1111",
        profilePic: "https://randomuser.me/api/portraits/men/27.jpg",
      },
      {
        id: 33,
        name: "Liam Lewis",
        phone: "+233 24 777 2222",
        profilePic: "https://randomuser.me/api/portraits/men/28.jpg",
      },
    ],
  },
  {
    id: 6,
    name: "Sarah Nelson",
    age: 31,
    phone: "+233 50 789 6543",
    email: "sarah.n@example.com",
    profilePic: "https://randomuser.me/api/portraits/women/6.jpg",
    invitees: [
      {
        id: 34,
        name: "Victoria Hall",
        phone: "+233 20 222 3333",
        profilePic: "https://randomuser.me/api/portraits/women/29.jpg",
      },
      {
        id: 35,
        name: "Logan Turner",
        phone: "+233 24 444 5555",
        profilePic: "https://randomuser.me/api/portraits/men/30.jpg",
      },
      {
        id: 36,
        name: "Eleanor Scott",
        phone: "+233 50 666 7777",
        profilePic: "https://randomuser.me/api/portraits/women/31.jpg",
      },
    ],
  },
];

export const transactions = [
  {
    description: "Airtime Purchase",
    id: "#12548796",
    type: "Airtime",
    card: "1234 ****",
    date: "28 Jan, 12:30 AM",
    amount: +60,
  },
  {
    description: "Withdrawal",
    id: "#12548796",
    type: "Transfer",
    card: "1234 ****",
    date: "25 Jan, 10:40 PM",
    amount: -750,
  },
  {
    description: "Mobile Service",
    id: "#12548796",
    type: "Service",
    card: "1234 ****",
    date: "20 Jan, 10:40 PM",
    amount: -150,
  },
  {
    description: "Wilson",
    id: "#12548796",
    type: "Transfer",
    card: "1234 ****",
    date: "15 Jan, 03:29 PM",
    amount: -1050,
  },
  {
    description: "Emilly",
    id: "#12548796",
    type: "Transfer",
    card: "1234 ****",
    date: "14 Jan, 10:40 PM",
    amount: 840,
  },
];
