export const users = [
  {
    id: 1,
    name: "John Doe",
    age: 28,
    phone: "+233 24 123 4567",
    email: "john.doe@example.com",
    profilePic: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 32,
    phone: "+233 50 987 6543",
    email: "jane.smith@example.com",
    profilePic: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 3,
    name: "Michael Johnson",
    age: 25,
    phone: "+233 20 456 7890",
    email: "michael.j@example.com",
    profilePic: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 4,
    name: "Emily Watson",
    age: 29,
    phone: "+233 55 654 3210",
    email: "emily.w@example.com",
    profilePic: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: 5,
    name: "David Lee",
    age: 35,
    phone: "+233 27 321 7890",
    email: "david.lee@example.com",
    profilePic: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: 6,
    name: "Sarah Connor",
    age: 27,
    phone: "+233 26 876 5432",
    email: "sarah.c@example.com",
    profilePic: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    id: 7,
    name: "James Brown",
    age: 40,
    phone: "+233 23 234 5678",
    email: "james.b@example.com",
    profilePic: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 8,
    name: "Sophia Martinez",
    age: 30,
    phone: "+233 56 789 0123",
    email: "sophia.m@example.com",
    profilePic: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    id: 9,
    name: "Daniel White",
    age: 33,
    phone: "+233 54 567 8901",
    email: "daniel.w@example.com",
    profilePic: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    id: 10,
    name: "Olivia Taylor",
    age: 26,
    phone: "+233 25 098 7654",
    email: "olivia.t@example.com",
    profilePic: "https://randomuser.me/api/portraits/women/10.jpg",
  },
];
